name: Tests and Coveralls

on: pull_request

jobs:
  coveralls:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        elixir: [1.14]
        otp: [25]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - uses: actions/cache@v1
        id: mix-cache-coverage
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install Mix Dependencies
        if: steps.mix-cache-coverage.outputs.cache-hit != 'true'
        run: | 
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix ecto.create
      - name: ===> Check coverage and tests
        run: mix coveralls.html
    services:
      database:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
